In [1]:
import pandas as pd
import matplotlib.pyplot as plt

/home/marcos/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [2]:
df = pd.read_csv("realGenAlgWrapperTests.csv")

In [3]:
df[df['accuracy'] == df['accuracy'].max()]

,accuracy,features,target,selection,crossover,population,generations,mutprob,crossprob,elitism,duration
47,0.780904,27,an,r,2,50,50,0.1,0.5,True,19.81

In [4]:
df.sort_values(by='accuracy', ascending=False).head()

,accuracy,features,target,selection,crossover,population,generations,mutprob,crossprob,elitism,duration
47,0.780904,27,an,r,2,50,50,0.10,0.5,True,19.81
29,0.780447,31,an,t,1,50,50,0.10,1.0,True,33.23
5,0.779807,29,an,t,2,20,50,0.10,0.5,True,6.34
46,0.779109,33,an,r,2,50,50,0.10,1.0,True,38.31
64,0.778593,29,an,r,1,50,50,0.05,1.0,True,30.76

In [6]:
df.sort_values(by='features', ascending=True).head()

,accuracy,features,target,selection,crossover,population,generations,mutprob,crossprob,elitism,duration
58,0.775695,23,an,r,1,50,20,0.10,1.0,True,12.54
33,0.754754,24,an,r,2,20,20,0.10,1.0,True,4.59
11,0.767612,24,an,t,2,50,20,0.05,0.5,True,7.98
25,0.775748,24,an,t,1,50,20,0.10,0.5,True,5.26
31,0.772768,26,an,t,1,50,50,0.05,1.0,True,31.70

In [40]:
df.sort_values(by='duration', ascending=True).head()

,accuracy,features,target,selection,crossover,population,generations,mutprob,crossprob,elitism,duration
19,0.776663,34,an,t,1,20,20,0.05,0.5,True,2.00
17,0.758497,26,an,t,1,20,20,0.10,0.5,True,2.11
1,0.760438,31,an,t,2,20,20,0.10,0.5,True,2.94
3,0.766333,27,an,t,2,20,20,0.05,0.5,True,3.13
18,0.767237,28,an,t,1,20,20,0.05,1.0,True,3.91

In [33]:
import docx

In [34]:
dfA

,accuracy,features,target,selection,crossover,population,generations,mutprob,crossprob,elitism,duration
5,0.779807,29,an,t,2,20,50,0.10,0.5,True,6.34
19,0.776663,34,an,t,1,20,20,0.05,0.5,True,2.00
14,0.776053,35,an,t,2,50,50,0.05,1.0,True,28.98
25,0.775748,24,an,t,1,50,20,0.10,0.5,True,5.26
7,0.773050,29,an,t,2,20,50,0.05,0.5,True,6.24

In [36]:

## Accuracy

docA = docx.Document()

# add a table to the end and create a reference variable
# extra row is so we can add the header row
t = doc.add_table(dfA.shape[0]+1, dfA.shape[1])

# add the header rows.
for j in range(dfA.shape[-1]):
    t.cell(0,j).text = dfA.columns[j]

# add the rest of the data frame
for i in range(dfA.shape[0]):
    for j in range(dfA.shape[-1]):
        t.cell(i+1,j).text = str(dfA.values[i,j])

# save the doc
docA.save('./accuracy.docx')

In [ ]:

## Variables

docV = docx.Document()

# add a table to the end and create a reference variable
# extra row is so we can add the header row
t = doc.add_table(dfV.shape[0]+1, dfV.shape[1])

# add the header rows.
for j in range(dfA.shape[-1]):
    t.cell(0,j).text = dfA.columns[j]

# add the rest of the data frame
for i in range(dfA.shape[0]):
    for j in range(dfA.shape[-1]):
        t.cell(i+1,j).text = str(dfA.values[i,j])

# save the doc
docA.save('accuracy.docx')

In [ ]:

accuracy	features	target	selection	crossover	population	generations	mutprob	crossprob	elitism	duration
5	0.779807	29	an	t	2	20	50	0.10	0.5	True	6.34
19	0.776663	34	an	t	1	20	20	0.05	0.5	True	2.00
14	0.776053	35	an	t	2	50	50	0.05	1.0	True	28.98
25	0.775748	24	an	t	1	50	20	0.10	0.5	True	5.26
7	0.773050	29	an	t	2	20	50	0.05	0.5	True	6.24